"""empty message

Revision ID: b7f77a84e6a2
Revises: 297040b0a36b
Create Date: 2022-04-12 12:01:52.128304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f77a84e6a2'
down_revision = '297040b0a36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_genres')
    op.drop_table('venue_genres')
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###

    op.execute('update venues set genres=\'{"Jazz", "Reggae", "Swing", "Classical", "Folk"}\' where id=1;')
    op.execute('update venues set genres=\'{"Classical", "R&B", "Hip-Hop"}\' where id=2;')
    op.execute('update venues set genres=\'{"Rock n Roll", "Jazz", "Classical", "Folk"}\' where id=3;')

    op.execute('update artists set genres=\'{"Rock n Roll"}\' where id=4;')
    op.execute('update artists set genres=\'{"Jazz"}\' where id=5;')
    op.execute('update artists set genres=\'{"Jazz", "Classical"}\' where id=6;')


    op.alter_column('venues','genres', nullable =False)
    op.alter_column('artists','genres', nullable =False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    op.create_table('venue_genres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='venue_genres_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='venue_genres_pkey')
    )
    op.create_table('artist_genres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='artist_genres_artist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='artist_genres_pkey')
    )
    # ### end Alembic commands ###
